// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhkrinjccselaidmgxwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpoa3JpbmpjY3NlbGFpZG1neHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Njk4MDQsImV4cCI6MjA2MzA0NTgwNH0.rPBMtVjlt0O1osQsa7WDIioQeJ3zQbLG0-xlZ6QI8iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);